services:
  liferay-postgresql:
    image: postgres:15.1
    volumes:
      - liferay_db:/var/lib/postgresql
      - liferay_data:/var/lib/postgresql/data
    networks:
      - liferay_back
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  liferay-pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "81:80"
    depends_on:
      - liferay-postgresql
    networks:
      - liferay_back
volumes:
  liferay_data:
  liferay_db:
  pgadmin_data:
networks:
  liferay_back:
